case class Point(x: Double, y: Double)

trait Marks:
    val markNames: Seq[String]

object HandMarks extends Marks:
    val markNames = Seq(
        "1st DP Proximal",
        "1st PP Distal",
        "1st PP Proximal",
        "1st MC Distal",
        "1st MC Proximal",
        "2nd DP Proximal",
        "2nd MP Distal",
        "2nd MP Proximal",
        "2nd PP Distal",
        "2nd PP Proximal",
        "2nd MC Distal",
        "2nd MC Proximal",
        "3rd DP Proximal",
        "3rd MP Distal",
        "3rd MP Proximal",
        "3rd PP Distal",
        "3rd PP Proximal",
        "3rd MC Distal",
        "3rd MC Proximal",
        "4th DP Proximal",
        "4th MP Distal",
        "4th MP Proximal",
        "4th PP Distal",
        "4th PP Proximal",
        "4th MC Distal",
        "4th MC Proximal",
        "5th DP Proximal",
        "5th MP Distal",
        "5th MP Proximal",
        "5th PP Distal",
        "5th PP Proximal",
        "5th MC Distal",
        "5th MC Proximal",
        // "1st Distal Phalanx Distal End",
        // "1st Distal Phalanx Proximal End",
        // "1st Proximal Phalanx Distal End",
        // "1st Proximal Phalanx Proximal End",
        // "2nd Distal Phalanx Distal End",
        // "2nd Distal Phalanx Proximal End",
        // "2nd Middle Phalanx Distal End",
        // "2nd Middle Phalanx Proximal End",
        // "2nd Proximal Phalanx Distal End",
        // "2nd Proximal Phalanx Proximal End",
        // "3rd Distal Phalanx Distal End",
        // "3rd Distal Phalanx Proximal End",
        // "3rd Middle Phalanx Distal End",
        // "3rd Middle Phalanx Proximal End",
        // "3rd Proximal Phalanx Distal End",
        // "3rd Proximal Phalanx Proximal End",
        // "4th Distal Phalanx Distal End",
        // "4th Distal Phalanx Proximal End",
        // "4th Middle Phalanx Distal End",
        // "4th Middle Phalanx Proximal End",
        // "4th Proximal Phalanx Distal End",
        // "4th Proximal Phalanx Proximal End",
        // "5th Distal Phalanx Distal End",
        // "5th Distal Phalanx Proximal End",
        // "5th Middle Phalanx Distal End",
        // "5th Middle Phalanx Proximal End",
        // "5th Proximal Phalanx Distal End",
        // "5th Proximal Phalanx Proximal End",
        // "1st Metacarpal Distal End",
        // "1st Metacarpal Proximal End",
        // "2nd Metacarpal Distal End",
        // "2nd Metacarpal Proximal End",
        // "3rd Metacarpal Distal End",
        // "3rd Metacarpal Proximal End",
        // "4th Metacarpal Distal End",
        // "4th Metacarpal Proximal End",
        // "5th Metacarpal Distal End",
        // "5th Metacarpal Proximal End",
        "Distal Radius",
        "Distal Ulna"
    )